"use client"

import { motion } from "framer-motion"
import { CheckCircle2, Clock, AlertTriangle, ShieldCheck, ArrowRight } from "lucide-react"
import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
} from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { RiskBadge } from "@/components/risk-badge"
import { RiskTier } from "@/components/risk-tier"
import type { RiskReportResult } from "@/lib/types"

function getScoreColor(score: number, max: number): string {
  const pct = max > 0 ? score / max : 0
  if (pct <= 0.2)  return "text-emerald-400"
  if (pct <= 0.51) return "text-amber-400"
  return "text-red-400"
}

function getScoreRing(score: number, max: number): string {
  const pct = max > 0 ? score / max : 0
  if (pct <= 0.2)  return "stroke-emerald-500"
  if (pct <= 0.51) return "stroke-amber-500"
  return "stroke-red-500"
}

interface RiskReportProps {
  report: RiskReportResult
  mode: "preview" | "verified"
  /** Called when user clicks the CTA to switch to verified mode */
  onRequestVerified?: () => void
}

export function RiskReport({ report, mode, onRequestVerified }: RiskReportProps) {
  const isPreview = mode === "preview"
  const pct = report.maxScore > 0 ? (report.overallScore / report.maxScore) * 100 : 0
  const circumference = 2 * Math.PI * 40

  return (
    <motion.div
      initial={{ opacity: 0, y: 40 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, ease: "easeOut" }}
      className="w-full max-w-2xl mx-auto"
    >
      {/* ── Preview warning banner — shown above card ── */}
      {isPreview && (
        <motion.div
          initial={{ opacity: 0, y: -8 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="mb-3 flex items-start gap-2.5 rounded-xl border border-amber-500/40 bg-amber-500/10 px-4 py-3"
        >
          <AlertTriangle className="h-4 w-4 text-amber-400 mt-0.5 shrink-0" />
          <div className="flex-1 space-y-1">
            <p className="text-xs font-semibold text-amber-300">
              ⚠️ Unverified AI Output
            </p>
            <p className="text-[11px] text-amber-300/70 leading-relaxed">
              This result was generated by AI from public sources only. It has{" "}
              <span className="font-semibold text-amber-300">not</span> been
              validated by GenLayer consensus and is{" "}
              <span className="font-semibold text-amber-300">not</span> stored
              on-chain. Do not rely on this for investment decisions.
            </p>
          </div>
        </motion.div>
      )}

      <Card
        className={`overflow-hidden backdrop-blur-xl ${
          isPreview
            ? "border-amber-500/25 bg-card/70"
            : "border-border/60 bg-card/80"
        }`}
      >
        {/* Preview watermark label */}
        {isPreview && (
          <div className="absolute top-3 right-3 z-10">
            <span className="rounded-full border border-amber-500/40 bg-amber-500/10 px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wider text-amber-400">
              AI Preview
            </span>
          </div>
        )}

        <CardHeader className="space-y-4 pb-4">
          <div className="flex flex-col items-center gap-4 sm:flex-row sm:justify-between">
            <div className="space-y-1 text-center sm:text-left">
              <div className="flex items-center gap-2">
                {isPreview ? (
                  <AlertTriangle className="h-4 w-4 text-amber-400" />
                ) : (
                  <ShieldCheck className="h-4 w-4 text-primary" />
                )}
                <h2 className="text-xl font-bold text-foreground">
                  {isPreview ? "AI Risk Preview" : "Verified Risk Assessment"}
                </h2>
              </div>
              <p className="text-sm text-muted-foreground">
                Analysis for{" "}
                <span className="font-semibold text-primary">
                  {report.projectName}
                </span>
              </p>
            </div>
            <RiskBadge level={report.overallRisk} />
          </div>

          {/* Score ring */}
          <div className="flex items-center justify-center py-2">
            <div className="relative h-28 w-28">
              <svg
                viewBox="0 0 100 100"
                className="h-full w-full -rotate-90"
                aria-hidden="true"
              >
                <circle
                  cx="50" cy="50" r="40"
                  fill="none"
                  className="stroke-secondary"
                  strokeWidth="6"
                />
                <motion.circle
                  cx="50" cy="50" r="40"
                  fill="none"
                  className={getScoreRing(report.overallScore, report.maxScore)}
                  strokeWidth="6"
                  strokeLinecap="round"
                  strokeDasharray={circumference}
                  initial={{ strokeDashoffset: circumference }}
                  animate={{
                    strokeDashoffset: circumference - (pct / 100) * circumference,
                  }}
                  transition={{ duration: 1.2, delay: 0.3, ease: "easeOut" }}
                />
              </svg>
              <div className="absolute inset-0 flex flex-col items-center justify-center">
                <motion.span
                  className={`text-2xl font-bold font-mono ${getScoreColor(report.overallScore, report.maxScore)}`}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: 0.6 }}
                >
                  {report.overallScore}
                </motion.span>
                <span className="text-[10px] uppercase tracking-wider text-muted-foreground">
                  / {report.maxScore}
                </span>
              </div>
            </div>
          </div>
        </CardHeader>

        <CardContent className="space-y-3">
          {Array.isArray(report.tiers) && report.tiers.map((tier, i) => (
            <RiskTier key={tier.id} tier={tier} index={i} />
          ))}
        </CardContent>

        <CardFooter className="flex flex-col gap-3 border-t border-border/40 pt-4">
          {/* Footer meta row */}
          <div className="flex w-full flex-col gap-2 sm:flex-row sm:justify-between">
            <div className="flex items-center gap-2 text-xs text-muted-foreground">
              {isPreview ? (
                <>
                  <AlertTriangle className="h-3.5 w-3.5 text-amber-400" />
                  <span>AI-only · Not validator-confirmed</span>
                </>
              ) : (
                <>
                  <CheckCircle2 className="h-3.5 w-3.5 text-primary" />
                  <span>
                    Validator Consensus ({report.validatorCount} validators)
                  </span>
                </>
              )}
            </div>
            <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
              <Clock className="h-3.5 w-3.5" />
              <span>{new Date(report.timestamp).toLocaleString()}</span>
            </div>
          </div>

          {/* Preview → Verified CTA */}
          {isPreview && onRequestVerified && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ delay: 0.8 }}
              className="w-full rounded-lg border border-primary/20 bg-primary/5 p-3"
            >
              <div className="flex items-start justify-between gap-3">
                <div className="space-y-0.5">
                  <p className="text-xs font-semibold text-foreground">
                    Get the validator-backed result
                  </p>
                  <p className="text-[11px] text-muted-foreground">
                    Submit this project to GenLayer consensus for a verified,
                    on-chain report.
                  </p>
                </div>
                <Button
                  size="sm"
                  className="shrink-0 h-8 text-xs"
                  onClick={onRequestVerified}
                >
                  Verify On-Chain
                  <ArrowRight className="ml-1.5 h-3 w-3" />
                </Button>
              </div>
            </motion.div>
          )}
        </CardFooter>
      </Card>
    </motion.div>
  )
}